{% set name = "eventlet" %}
{% set version = "0.33.3" %}
{% set bundle = "tar.gz" %}
{% set hash = "722803e7eadff295347539da363d68ae155b8b26ae6a634474d0a920be73cfda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - greenlet >=0.3
    - dnspython >=1.15.0
    - six >=1.10.0
    - pyopenssl

test:
  imports:
    - eventlet
    - eventlet.green
    - eventlet.green.OpenSSL
    - eventlet.green.http
    - eventlet.green.urllib
    - eventlet.greenio
    - eventlet.hubs
    - eventlet.support
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://eventlet.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library
  dev_url: https://github.com/eventlet/eventlet
  doc_url: http://eventlet.net

extra:
  recipe-maintainers:
    - synapticarbors
    - anguslees
