{% set name = "eventlet" %}
{% set version = "0.35.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "3b2eede94d64538cb894eec50302a881e056ed7e057f0e24fb45b28a19d6b2e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
  run:
    - python >=3.7
    - greenlet >=1.0
    - dnspython >=1.15.0
    - pyopenssl

test:
  imports:
    - eventlet
    - eventlet.green
    - eventlet.green.OpenSSL
    - eventlet.green.http
    - eventlet.green.urllib
    - eventlet.greenio
    - eventlet.hubs
    - eventlet.support
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://eventlet.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Highly concurrent networking library
  dev_url: https://github.com/eventlet/eventlet
  doc_url: http://eventlet.net

extra:
  recipe-maintainers:
    - synapticarbors
    - anguslees
